version: 2

builds:
  - main: ./cmd/tunnelman
    binary: tunnelman
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/takaaki-s/tunnelman/cmd/tunnelman/cmd.Version={{.Version}}

archives:
  - format: tar.gz

changelog:
  sort: asc
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Refactoring"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Testing"
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: "Others"
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
      - "^Merge"
      - "^merge"
